# Generated by Django 4.2.15 on 2024-08-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0002_book_image_book_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorobj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='author.author'),
            preserve_default=False,
        ),
    ]
